backend:
  name: github
  repo: cinyuzhu/damic-notes
  branch: main
  auth_type: oauth
  app_id: Ov23libEVoBM9FREDJo9  # from GitHub

media_folder: "docs/uploads"
public_folder: "/uploads"

collections:
  - name: "notes"
    label: "Notes"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
